# Generated by Django 3.0.5 on 2020-05-17 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenght', models.IntegerField(verbose_name='Длина, см')),
                ('width', models.IntegerField(verbose_name='Ширина, см')),
                ('height', models.IntegerField(verbose_name='Высота, см')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название (текущий или архивный)')),
            ],
        ),
        migrations.CreateModel(
            name='DreamcatcherOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.IntegerField(verbose_name='Длина, см')),
            ],
        ),
        migrations.CreateModel(
            name='LetterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenght', models.IntegerField(verbose_name='Длина, см')),
                ('width', models.IntegerField(verbose_name='Ширина, см')),
                ('color', models.CharField(choices=[('Белый', 'Белый'), ('Крафтовый', 'Крафтовый')], max_length=40, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='Фамилия, Имя, Очество')),
                ('post_address', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('mail', models.EmailField(max_length=100, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='girafic_app/img', verbose_name='Фото')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('lenght', models.IntegerField(verbose_name='Длина, см')),
                ('width', models.IntegerField(verbose_name='Ширина, см')),
                ('color', models.CharField(choices=[('Белый', 'Белый'), ('Крафтовый', 'Крафтовый')], max_length=40, verbose_name='Цвет')),
                ('cost', models.IntegerField(verbose_name='Цена, руб.')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girafic_app.Catalog', verbose_name='Каталог')),
            ],
        ),
        migrations.CreateModel(
            name='Dreamcatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='girafic_app/img', verbose_name='Фото')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('diameter', models.IntegerField(verbose_name='Длина, см')),
                ('cost', models.IntegerField(verbose_name='Цена, руб.')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girafic_app.Catalog', verbose_name='Каталог')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='girafic_app/img', verbose_name='Фото')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('lenght', models.IntegerField(verbose_name='Длина, см')),
                ('width', models.IntegerField(verbose_name='Ширина, см')),
                ('height', models.IntegerField(verbose_name='Высота, см')),
                ('cost', models.IntegerField(verbose_name='Цена, руб.')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girafic_app.Catalog', verbose_name='Каталог')),
            ],
        ),
    ]
