# Generated by Django 3.0.5 on 2020-05-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girafic_app', '0003_auto_20200518_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxorder',
            options={'verbose_name': 'Заказ коробок', 'verbose_name_plural': 'Заказы коробок'},
        ),
        migrations.AlterModelOptions(
            name='dreamcatcherorder',
            options={'verbose_name': 'Заказ ловцов снов', 'verbose_name_plural': 'Заказы ловцов снов'},
        ),
        migrations.AlterModelOptions(
            name='letterorder',
            options={'verbose_name': 'Заказ письма', 'verbose_name_plural': 'Заказы писем'},
        ),
    ]
