# Generated by Django 3.0.6 on 2020-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girafic_app', '0004_auto_20200519_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.FloatField(verbose_name='Высота, см'),
        ),
        migrations.AlterField(
            model_name='box',
            name='lenght',
            field=models.FloatField(verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.FloatField(verbose_name='Ширина, см'),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='height',
            field=models.FloatField(verbose_name='Высота, см'),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='lenght',
            field=models.FloatField(verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='width',
            field=models.FloatField(verbose_name='Ширина, см'),
        ),
        migrations.AlterField(
            model_name='dreamcatcher',
            name='diameter',
            field=models.FloatField(verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='dreamcatcherorder',
            name='diameter',
            field=models.FloatField(verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='lenght',
            field=models.FloatField(verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='width',
            field=models.FloatField(verbose_name='Ширина, см'),
        ),
        migrations.AlterField(
            model_name='letterorder',
            name='lenght',
            field=models.FloatField(verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='letterorder',
            name='width',
            field=models.FloatField(verbose_name='Ширина, см'),
        ),
    ]
