# Generated by Django 3.0.6 on 2020-05-22 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girafic_app', '0005_auto_20200520_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='dreamcatcher',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='letter',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='box',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box', to='girafic_app.Catalog', verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='dreamcatcher',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreamcatcher', to='girafic_app.Catalog', verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='girafic_app.Catalog', verbose_name='Каталог'),
        ),
    ]
