# Generated by Django 3.0.6 on 2020-05-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girafic_app', '0007_auto_20200526_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(blank=True, default=False, verbose_name='выполнен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='clientdata',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_with_box', to='girafic_app.Order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='girafic_app.Order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='dreamcatcherorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_with_dreamcatcher', to='girafic_app.Order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='letterorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_with_letter', to='girafic_app.Order', verbose_name='Заказ'),
        ),
    ]
