# Generated by Django 3.0.6 on 2020-05-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girafic_app', '0008_auto_20200526_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdata',
            options={'verbose_name': 'Клиент дата'},
        ),
    ]
