# Generated by Django 3.0.6 on 2020-05-26 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girafic_app', '0009_auto_20200526_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxorder',
            name='height',
            field=models.FloatField(blank=True, verbose_name='Высота, см'),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='lenght',
            field=models.FloatField(blank=True, verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_with_box', to='girafic_app.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='width',
            field=models.FloatField(blank=True, verbose_name='Ширина, см'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='girafic_app.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='dreamcatcherorder',
            name='diameter',
            field=models.FloatField(blank=True, verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='dreamcatcherorder',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_with_dreamcatcher', to='girafic_app.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='letterorder',
            name='color',
            field=models.CharField(blank=True, choices=[('Белый', 'Белый'), ('Крафтовый', 'Крафтовый')], max_length=40, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='letterorder',
            name='lenght',
            field=models.FloatField(blank=True, verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='letterorder',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_with_letter', to='girafic_app.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='letterorder',
            name='width',
            field=models.FloatField(blank=True, verbose_name='Ширина, см'),
        ),
    ]
